scripts:
  # aggregate_min.py:
  #     output: data/aggregated/season_2013_agg_min_tformer_{{ get_date() }}.csv
  # reformat_dataset.py:
  #     input: data/aggregated/season_2013_agg_min_tformer_{{ get_date() }}.csv
  #     output: data/aggregated/season_2013_agg_reformatted_tformer_{{ get_date() }}.csv
  # rescale.py:
  #     input: data/aggregated/season_2013_agg_reformatted_tformer_{{ get_date() }}.csv
  #     output: data/aggregated/season_2013_agg_scaled_tformer_{{ get_date() }}.csv
  # calculate_metrics.py:
  #     input: data/aggregated/season_2013_agg_scaled_tformer_{{ get_date() }}.csv
  #     output: data/aggregated/season_2013_agg_metrics_tformer_{{ get_date() }}.csv
  # cleanup_data.py:
  #     input: data/aggregated/season_2013_agg_metrics_tformer_{{ get_date() }}.csv
  #     output: data/aggregated/season_2013_agg_cleaned_tformer_{{ get_date() }}.csv
  # calculate_suspense.py:
  #     input: data/aggregated/season_2013_agg_cleaned_tformer_{{ get_date() }}.csv
  #     output: data/aggregated/season_2013_agg_suspense_tformer_{{ get_date() }}.csv
  # calculate_sim_metrics.py:
  #     input: data/aggregated/season_2013_agg_suspense_tformer_{{ get_date() }}.csv
  #     output: data/aggregated/season_2013_agg_sim_results_tformer_{{ get_date() }}.csv
  # recalculate_redcards.py:
  #     input: data/aggregated/season_2013_agg_sim_results_tformer_{{ get_date() }}.csv
  #     output: data/aggregated/season_2013_agg_final_tformer_{{ get_date() }}.csv
  remove_and_reorder.py:
      input: data/aggregated/season_2013_agg_final_tformer_2024-01-02T20:12:25.csv
      output: data/aggregated/season_2013_agg_final_processed_tformer_{{ get_date() }}.csv
  split_team_files.py:
      input: data/aggregated/season_2013_agg_final_processed_tformer_{{ get_date() }}.csv
      output: data/aggregated/team_data_tformer/2024-01-03
